use polyfill_rs::Result;
use serde_json::Value;
use colored::*;

#[tokio::main]
async fn main() -> Result<()> {
    let client = reqwest::Client::builder()
        .user_agent("WhaleScanner/2.0")
        .build()?;

    // --- SETTINGS ---
    let user_address = "0x63ce342161250d705dc0b16df89036c8e5f9ba9a"; 
    // ----------------

    println!("\n══════════════════════════════════════════════════════");
    println!("       USER IDENTITY DECODER");
    println!("       WALLET: {}", user_address.cyan());
    println!("══════════════════════════════════════════════════════\n");

    let url = format!("https://gamma-api.polymarket.com/public-profile?address={}", user_address);
    let resp = client.get(&url).send().await?;

    if resp.status().is_success() {
        let profile: Value = resp.json().await?;

        // 1. Fetch Display Name (Username)
        let display_name = profile["name"].as_str().unwrap_or("None Set");
        
        // 2. Fetch Pseudonym (Auto-generated by Poly)
        let pseudonym = profile["pseudonym"].as_str().unwrap_or("Unknown");

        // 3. Check for X (Twitter) integration
        let x_handle = profile["xUsername"].as_str();
        let x_display = x_handle.unwrap_or("Not Linked");

        // --- CLICKABLE LINK LOGIC ---
        // Poly Link
        let poly_url = format!("https://polymarket.com/profile/{}", user_address);
        let poly_link = format!("\x1b]8;;{}\x1b\\{}\x1b]8;;\x1b\\", poly_url, display_name);

        // X Link
        let x_link = if let Some(handle) = x_handle {
            let x_url = format!("https://x.com/{}", handle);
            format!("\x1b]8;;{}\x1b\\{}\x1b]8;;\x1b\\", x_url, x_display)
        } else {
            x_display.to_string()
        };

        // --- DISPLAY MENU ---
        println!("👤 Username:     {}", poly_link.green().bold());
        println!("🎭 Pseudonym:    {}", pseudonym.dimmed());
        println!("🐦 X / Twitter:  {}", x_link.blue());

        if display_name == "None Set" {
            println!("\nℹ️  {} This User is anonymous (using default wallet address).", "NOTICE:".dimmed());
        } else {
            println!("\n⭐ {} This is a public/social trader.", "REPUTATION:".yellow());
        }

    } else {
        println!("{} Profile not initialized on Gamma.", "ERROR:".red());
    }

    println!("\n══════════════════════════════════════════════════════\n");

    Ok(())
}